PersonelOdevi/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelOdevi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForExampleDBEntities : DbContext
    {
        public ForExampleDBEntities()
            : base("name=ForExampleDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
    }
}

PersonelOdevi/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Toshiba\source\repos\PersonelOdevi\PersonelOdevi\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

PersonelOdevi/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

PersonelOdevi/Models/User.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelOdevi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Ad { get; set; }
        public string SoyAd { get; set; }
        public System.DateTime DogumTarihi { get; set; }
        public int Telefon { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public System.DateTime IseGirisTarihi { get; set; }
        public string Unvan { get; set; }
    }
}

PersonelOdevi/Controllers/ForExampleController.cs
using PersonelOdevi.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PersonelOdevi.Controllers
{
    public class ForExampleController : Controller
    {
        ForExampleDBEntities db = new ForExampleDBEntities();
        public ActionResult Index()
        {
            List<User> users = db.Users.ToList();
            return View(users);
        }
        public ActionResult Update(int id)
        {
            User user=db.Users.Find(id);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int id)
        {

            var user = db.Users.Find(id);
            db.Users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



    }

PersonelOdevi/Views/ForExample/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

PersonelOdevi/Views/ForExample/Index.cshtml
@model List<PersonelOdevi.Models.User>
@{
    ViewBag.Title = "Index";
}

<div class="card">
    <div class="card-header">
        <h2>Personeller</h2>
        <div class="card-body">
            <table class="table table-striped">              
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>AD</th>
                        <th>SOYAD</th>
                        <th>Doğum Tarihi</th>
                        <th>Email</th>
                        <th>Adres</th>
                        <th>Ise Giris Tarihi</th>
                        <th>Unvan</th>
                        <th>Edit</th>

                    </tr>
                    
                </thead>
                <tboy>
                    @foreach (var user in Model)
                    {
                    <tr>
                        <td>@user.ID</td>
                        <td>@user.Ad</td>
                        <td>@user.SoyAd</td>
                        <td>@user.DogumTarihi</td>
                        <td>@user.Email</td>
                        <td>@user.Adres</td>
                        <td>@user.IseGirisTarihi</td>
                        <td>@user.Unvan</td>
                        @Html.ActionLink("Update", "Update" ,new { id = user.ID },
                         new {@class="btn btn-xs btn-warning"})
                        @Html.ActionLink("Delete", "Delete" ,new { id = user.ID },
                         new { @class = "btn btn-xs btn-warning" })

                    </tr>
                    }
                </tboy>
            </table>
        </div>
    </div>
</div>

PersonelOdevi/Views/ForExample/Update.cshtml
@model PersonelOdevi.Models.User
@{
    ViewBag.Title = "Update";
}

@using (@Html.BeginForm("Update", "ForExample", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(x => x.ID)
        @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
        <br />
        @Html.Label("AD")
        @Html.TextBoxFor(x => x.Ad, new { @class = "form-control" })
        <br />
        @Html.Label("SOYAD")
        @Html.TextBoxFor(x => x.SoyAd, new { @class = "form-control" })
        <br />
        @Html.Label("DOĞUM TARİHİ")
        @Html.TextBoxFor(x => x.DogumTarihi, new { @class = "form-control" })
        <br />
        @Html.Label("TELEFON")
        @Html.TextAreaFor(x => x.Telefon, new { @class = "form-control" })
        <br />
        <br />
        @Html.Label("EMAİL")
        @Html.TextAreaFor(x => x.Email, new { @class = "form-control" })
        <br />
        <br />
        @Html.Label("ADRES")
        @Html.TextAreaFor(x => x.Adres, new { @class = "form-control" })
        <br />
        <br />
        @Html.Label("İŞE GİRİŞ TARİHİ")
        @Html.TextAreaFor(x => x.IseGirisTarihi, new { @class = "form-control" })
        <br />
        <br />
        @Html.Label("ÜNVAN")
        @Html.TextAreaFor(x => x.Unvan, new { @class = "form-control" })
        <br />
        <button class="btn btn-primary">Güncelle</button>
    </div>
}

PersonelOdevi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>